/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnits_Tslib_ValidateType */

#ifndef _Included_com_example_jnits_Tslib_ValidateType
#define _Included_com_example_jnits_Tslib_ValidateType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
